#!/usr/bin/env bash

# it432 package setup script
# Seung Geol Choi, May 2021 


sudo apt install -y git jq curl coreutils diffutils dconf-cli openssh-client node-json5 moreutils gcc g++ perl gitk gdb x11-utils make python3-pip net-tools python3-scapy wireshark-qt

pip3 install pycryptodome
